### ISSUE TITLE
Additional uglify features (source mapping)

### ISSUE THREAD

**Issue by khullah** [ionutvmi/uglifyjs-folder#11]
Is there a way to also generate source-maps or mangle files? Put it another way, can I use uglify's own options? This would make this project AWESOME (more than it is now).

**Comment by khullah** [comment]
Ok, I understood now that is possible with the config file.
However, the sourceMap didnt work for me:

```
{
  "compress": true,
  "mangle": true,
  "sourceMap": "root",
  "timings": true
}
```

Results in this error:
> node_modules\uglifyjs-folder\index.js:65
>         throw minifyResult.error;
>         ^
> DefaultsError: `0` is not a supported option

**Comment by khullah** [comment]
Not sure if it stuck with some option I previously used, but my latest finding is this:

```
{
  "compress": true,
  "output": "every.min.js"
}
```

when

```cls && uglifyjs-folder "%CD%" --configFile "uglify.config.json"```

results error:

```node_modules\uglifyjs-folder\index.js:65
        throw minifyResult.error;
        ^

TypeError: Cannot create property 'source_map' on string 'all.min.js'```

(still references ```all.min.js```, but i've changed to ```every.min.js```)

**Comment by ionutvmi** [comment]
Support for this has been added in 1.5.0

Please update your local version and review the readme file.
If you still have issues feel free to reopen the issue.

**Comment by khullah** [comment]
Thanks @ionutvmi. It still throws the same error for me, only now with ```every.min.js```. I'm having trouble using uglify-js cli as well, maybe is a issue with their code. I don't understand how I'm going to set every source-map filename as a rule for all the input, neither with u-folder or piping ```dir | uglify-js```.

Also, just noticed that to use the options --version and --help one should provide a path just the same, thought you might want to know that.

**Comment by ionutvmi** [comment]
@khullah if you want to have a specific file name you should provide that name using the --output parameter.
The file name from the uglifyjs is ignored when using this package.

**Comment by khullah** [comment]
I want to be the same as the input name, actually. X.js -> ./x.min.js +
./sourcemaps/x.js.map. How could I achieve that?

**Comment by ionutvmi** [comment]
If the generated file is x.min.js then the generated source map will be x.min.js.map

It should be sufficient to add the sourceMap property in the configuration file and set-up the url:

Something like:
```
{
    "sourceMap": {
        "url": "{file}.map"
    }
}
```

The command should be
```
uglifyjs-folder myFolder --config-file=uglifyconfig.json --output=x.min.js
```

**Comment by khullah** [comment]
Ok, that worked!
I've figured it out when that error ocurred: when output was inside config file.
Using it directly as parameter on CLI worked. Thanks for the help!
