### ISSUE TITLE
ignore min.js

### ISSUE THREAD

**Issue by HejieShao** [ionutvmi/uglifyjs-folder#13]
I use this command, but it can not ignore min.js in folder1. If I want to igonre min.js in folder1, what should I do?
```
uglifyjs-folder folder1 --each --extension .js --output folder2 --pattern "**/*.js,!**/*.min.js"
```

**Comment by ionutvmi** [comment]
I just tested that locally and it worked correctly

Are you using the latest version of uglify js (1.5.0) ?

**Comment by ionutvmi** [comment]
Closing this, assuming that it was fixed.
