### ISSUE TITLE
Can't ignore console.log

### ISSUE THREAD

**Issue by pranavq212** [ionutvmi/uglifyjs-folder#14]
It is more than new feature request then issue. 

`uglifyjs `can support removal of `console.log` using `-c, --compress [options] `while minfying like:
`uglifyjs app.js -m -c drop_console=true -o app.min.js`

 `uglifyjs-folder` did not support removal of pure functions.

Is it possible to add that support in here?

**Comment by ionutvmi** [comment]
You should be able to provide the uglifyjs options via the `--config-file` parameter

**Comment by kontur** [comment]
For anybody finding this:

`$ uglify-folder --config-file uglifyjs.config.json ...other options...`

and with `uglifyjs.config.json`:

```
{
  "compress": {
    "drop_console": true
  }
}
``` 
And all options available here from the [API reference](https://terser.org/docs/api-reference#compress-options).
