### ISSUE TITLE
same options as on uglify-js

### ISSUE THREAD

**Issue by ungalcrys** [ionutvmi/uglifyjs-folder#15]
I think it would be better if it would have the same options as uglify-js, mostly because it will make the transition easier and also give us the possibility to compress, mangle, etc.

**Comment by ionutvmi** [comment]
The `--config-file` parameter should allow you to setup all the necessary parameters for compressing and mangling. 

```
uglifyjs-folder test-folder --config-file "./uglify.json"
```

You can find more details in the readme.
