### ISSUE TITLE
Error: EMFILE: Too many opened files.

### ISSUE THREAD

**Issue by CRACKISH** [ionutvmi/uglifyjs-folder#16]
My folder has more 5000 js. And when i start **uglifyjs-folder** i have error: **Error: EMFILE: Too many opened files**. 

My fix:

```
function writeFile(filePath, code) {

  mkdirp(path.dirname(filePath), function () {
    try {
		fs.writeFileSync(filePath, code);
		console.log('File ' + filePath + ' written successfully !');
	} catch(err) {
		console.log('Error: ' + err);
	}
  });
}
```

**Comment by ionutvmi** [comment]
I have replaced the fs module with graceful-fs.
That should fix your issue while keeping the writing of the files in parallel.

Please let me know if you still encounter issues.
