### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by corysimmons** [ionutvmi/uglifyjs-folder#2]
```
$ node_modules/.bin/uglifyjs-folder ./assets/scripts -o ./dist/scripts
env: node\r: No such file or directory
```

**Comment by corysimmons** [comment]
`./assets/scripts` and `./dist/scripts` both exist.

I've tried it without the `./` as well.

**Comment by ionutvmi** [comment]
Can you please provide more details about your environment ?
node version, OS

**Comment by corysimmons** [comment]
Node 7+, OSX Yosemite

I ended up making something for my purposes: https://github.com/corysimmons/uglify-dir

Forgot to test if nesting worked, but I can revisit that if anyone is interested or the need arises for me.

**Comment by ionutvmi** [comment]
After a closer look here that command is trying to minify all the javascript files into one. 
Currently the file is created if the parent folder exists. 
In your case `/dist` folder doesn't exists and you receive that error.
Something like this `node_modules/.bin/uglifyjs-folder ./assets/scripts -o ./scripts.min.js` should work.

Looking at the parameters you want to create a new folder and for that you need to pass the `-e` flag.
Something like this should do the trick:
```
node_modules/.bin/uglifyjs-folder ./assets/scripts -eo ./dist/scripts
```
