### ISSUE TITLE
Update extend dependency version

### ISSUE THREAD

**Issue by luzzardi** [ionutvmi/uglifyjs-folder#21]
Installing the module and running npm audit is throwing 1 moderate security vulnerability message related to the package extend.

Moderate:  Prototype Pollution                        
Package: extend
Patched in: >=2.0.2 <3.0.0 || >=3.0.2
Dependency of: uglifyjs-folder
Path: uglifyjs-folder > extend

**Comment by ionutvmi** [comment]
this has ben fixed in 1.5.2
Please reopen if you still encounter issues.
