### ISSUE TITLE
ECMAScript 2021 not supported

### ISSUE THREAD

**Issue by 3rChuss** [ionutvmi/uglifyjs-folder#25]
First, thanks for awesome repository.

I started to use your npm, and it is not fully supporting ECMAScript 2021

I think teser needs to be updated?
One of the errors when using ES21 like: 

`errorDivs?.map((element) => { ... }
`
> Q [SyntaxError]: Unexpected token: punc (.)
> uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1:19541)
> uglifyjs-folder\index.js:50
        throw minifyResult.error;

Hope you guys can solve it, such a nice package.

**Comment by 3rChuss** [comment]
👏👏👏

**Comment by ionutvmi** [comment]
Hi @3rChuss ,

v3.0.0 has been published to npm.
Can you please try it locally and let me know if it works for you ?

**Comment by 3rChuss** [comment]
Hi @ionutvmi, yeah it is working!, thank you!
