### ISSUE TITLE
Add support for uglify-js-harmony

### ISSUE THREAD

**Issue by icl7126** [ionutvmi/uglifyjs-folder#3]
Hi, could you add support for 'uglify-js-harmony'? It supports partially ES6.
Like some switch -es6
All you need to do is add dev dependency `uglify-js-harmony": "^2.6.2` and then require it in your `index.js` file `var uglifyJS = require('uglify-js-harmony');`

**Comment by ionutvmi** [comment]
Support has been added in v1.1.0 via the --harmony flag.
