### ISSUE TITLE
Sourcemaps "sources" value incorrect when dealing with nested folders

### ISSUE THREAD

**Issue by sneiland** [ionutvmi/uglifyjs-folder#32]
Assuming a folder structure of

- source/js
- - index.js
- - folder
- - - something.js

with a desired output of

- destination/js
- - index.min.js
- - index.min.js.map
- - folder
- - - something.min.js
- - - something.min.js.map

I have configured a script in my package.json

`"minify:js": "uglifyjs-folder source/js -eo destination/js --config-file \"./uglifyjs.json\"",`

and a uglifyjs.json config file containing

`
{
  "sourceMap": {
    "filename": "{file}",
    "includeSources": true,
	"url": "{file}.map",
	"root": ""
  }
}
`

The files are created and named correctly however the source map generated for js files in nested folders is not correct.

If I look at the sourcemap for index.js I see "sources" array contains ["index.js"] which I understand to be correct. 

However if I look at the sourcemap generated for something.js I see the "sources" array contains a value ["folder/something.js"]. Note the inclusion of the parent folder name even though the source map is in the same relative folder as it js file it references.

**Comment by ionutvmi** [comment]
I pushed a change in v3.1.0

Can you try on your side when you have some time and let me know if it was fixed ?
