### ISSUE TITLE
Upgrade terser to > 5.14.1 to fix security issue potential regexp DDOS 

### ISSUE THREAD

**Issue by speich** [ionutvmi/uglifyjs-folder#33]
Terser insecure use of regular expressions before v4.8.1 and v5.14.2 leads to ReDoS - https://github.com/advisories/GHSA-4wf5-vphf-c2xc

**Comment by ionutvmi** [comment]
This has been published in 3.1.3

Thank you for reporting it.

**Comment by speich** [comment]
Actually, it was thanks to https://github.com/dependabot
