### ISSUE TITLE
Fails if run alongside other CLI scripts

### ISSUE THREAD

**Issue by hirasso** [ionutvmi/uglifyjs-folder#4]
Hi there, thank you for your effort! I have a weird problem. When running this:
```
uglifyjs-folder dist/js -e --extension .js -o dist/js --compress --mangle
```
...everything works as expected. This also works just fine:
```
echo 'test' | uglifyjs-folder dist/js -e --extension .js -o dist/js --compress --mangle 
```
...but this doesn't: 
```
uglifyjs-folder dist/js -e --extension .js -o dist/js --compress --mangle | echo 'test'
```
Only difference here is, that I moved ` | echo 'test'` to the end. Any ideas?

I need this because I have other scripts being called in my build script.

**Comment by hirasso** [comment]
So, the issue seems to be the `|` operator. When using `;` between commands, everything works just fine.

**Comment by ionutvmi** [comment]
The issue here is that `echo 'x'` doesn't accept the stdin when you provide a parameter to it.
There should be an error message in the console about that.

Echo is just an example here but you need to ensure that the following command accepts stdin input.
Something like this should work:
```
uglifyjs-folder dist/js -e --extension .js -o dist/js | echo
```
