### ISSUE TITLE
feature: exclude folder/files

### ISSUE THREAD

**Issue by rchovan** [ionutvmi/uglifyjs-folder#5]
Hi, 
could you please implement feature like exclude folders or files ? . 
Because in one www folder, I have big library OpenUI5 which is already minified. 

Thank You.

**Comment by ionutvmi** [comment]
Added support for custom patterns in 1.2.0.

Please let me know if it works ok for you.

**Comment by rchovan** [comment]
Hi, 
it tried some time to find the correct pattern, but it works. Could you please upload it to npm repository ? 

Thank You.

**Comment by rchovan** [comment]
Hi, 
it works. 

Thank You.
