### ISSUE TITLE
Feature: uglify config file

### ISSUE THREAD

**Issue by jkruse** [ionutvmi/uglifyjs-folder#6]
I would be really nice, if it was possible to configure UglifyJS, because default configuration doesn't always work. One way to do that would be to upgrade to UglifyJS 3.x and add support for just the --config-file option. That way everything could be configured in a file.

**Comment by ionutvmi** [comment]
I will look over upgrading to UglifyJS 3 this weekend.

**Comment by ionutvmi** [comment]
Starting with 1.4.0 you can use --config-file to add options to the uglifyjs minifier.
