### ISSUE TITLE
Keep Function Names

### ISSUE THREAD

**Issue by andresinspace** [ionutvmi/uglifyjs-folder#8]
How do we pass this option --keep-fnames from UglyJS3?

I am seemingly having different results from minififying my JS through uglyJS3 compared to this(uglyjs-folder)

**Comment by ionutvmi** [comment]
we are still using uglifyjs 2 at the moment.
I am planning on upgrading to uglifyjs3 soon.

**Comment by ionutvmi** [comment]
Starting with 1.4.0 you can use --config-file to add options to the uglifyjs minifier.
